//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.26 at 10:34:50 AM EDT 
//


package hello.wsdl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ArrayOfProfileOtherServiceLink complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArrayOfProfileOtherServiceLink">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProfileOtherServiceLink" type="{http://schemas.datacontract.org/2004/07/EP.Core.Services.AdminGatewayService.API.Contracts.Data}ProfileOtherServiceLink" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrayOfProfileOtherServiceLink", propOrder = {
    "profileOtherServiceLink"
})
public class ArrayOfProfileOtherServiceLink {

    @XmlElement(name = "ProfileOtherServiceLink", nillable = true)
    protected List<ProfileOtherServiceLink> profileOtherServiceLink;

    /**
     * Gets the value of the profileOtherServiceLink property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the profileOtherServiceLink property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProfileOtherServiceLink().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProfileOtherServiceLink }
     * 
     * 
     */
    public List<ProfileOtherServiceLink> getProfileOtherServiceLink() {
        if (profileOtherServiceLink == null) {
            profileOtherServiceLink = new ArrayList<ProfileOtherServiceLink>();
        }
        return this.profileOtherServiceLink;
    }

}
