//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.26 at 10:34:50 AM EDT 
//


package hello.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CustomLinkResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CustomLinkResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.datacontract.org/2004/07/EP.Core.Services.AdminGatewayService.API.Contracts.Data}ResponseComposite">
 *       &lt;sequence>
 *         &lt;element name="BaseURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Encode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Genre" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HideHelperFor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HideIfFullText" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="LinkCategory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LinkIcon" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LinkKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LinkName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LinkSourceId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NewWindow" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PrimaryProxy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ProxyURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="QueryString" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReqCatalogHoldingFields" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReqFields" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SecondaryProxy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ShowIfLocal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ShowOnCatalogHoldingTable" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ShowOnControlPanel" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ShowOnDetailDisplay" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ShowOnLinkSource" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ShowOnPubFinderDetails" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ShowOnPubFinderResults" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ShowOnPublicationList" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ShowOnResultList" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="TargetUsesRefUrl" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="UseProxy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="WindowName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="WindowParams" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustomLinkResponse", propOrder = {
    "baseURL",
    "encode",
    "genre",
    "hideHelperFor",
    "hideIfFullText",
    "linkCategory",
    "linkIcon",
    "linkKey",
    "linkName",
    "linkSourceId",
    "newWindow",
    "primaryProxy",
    "proxyURL",
    "queryString",
    "reqCatalogHoldingFields",
    "reqFields",
    "secondaryProxy",
    "showIfLocal",
    "showOnCatalogHoldingTable",
    "showOnControlPanel",
    "showOnDetailDisplay",
    "showOnLinkSource",
    "showOnPubFinderDetails",
    "showOnPubFinderResults",
    "showOnPublicationList",
    "showOnResultList",
    "targetUsesRefUrl",
    "useProxy",
    "windowName",
    "windowParams"
})
public class CustomLinkResponse
    extends ResponseComposite
{

    @XmlElementRef(name = "BaseURL", namespace = "http://schemas.datacontract.org/2004/07/EP.Core.Services.AdminGatewayService.API.Contracts.Data", type = JAXBElement.class)
    protected JAXBElement<String> baseURL;
    @XmlElementRef(name = "Encode", namespace = "http://schemas.datacontract.org/2004/07/EP.Core.Services.AdminGatewayService.API.Contracts.Data", type = JAXBElement.class)
    protected JAXBElement<String> encode;
    @XmlElementRef(name = "Genre", namespace = "http://schemas.datacontract.org/2004/07/EP.Core.Services.AdminGatewayService.API.Contracts.Data", type = JAXBElement.class)
    protected JAXBElement<String> genre;
    @XmlElementRef(name = "HideHelperFor", namespace = "http://schemas.datacontract.org/2004/07/EP.Core.Services.AdminGatewayService.API.Contracts.Data", type = JAXBElement.class)
    protected JAXBElement<String> hideHelperFor;
    @XmlElement(name = "HideIfFullText")
    protected Boolean hideIfFullText;
    @XmlElementRef(name = "LinkCategory", namespace = "http://schemas.datacontract.org/2004/07/EP.Core.Services.AdminGatewayService.API.Contracts.Data", type = JAXBElement.class)
    protected JAXBElement<String> linkCategory;
    @XmlElementRef(name = "LinkIcon", namespace = "http://schemas.datacontract.org/2004/07/EP.Core.Services.AdminGatewayService.API.Contracts.Data", type = JAXBElement.class)
    protected JAXBElement<String> linkIcon;
    @XmlElementRef(name = "LinkKey", namespace = "http://schemas.datacontract.org/2004/07/EP.Core.Services.AdminGatewayService.API.Contracts.Data", type = JAXBElement.class)
    protected JAXBElement<String> linkKey;
    @XmlElementRef(name = "LinkName", namespace = "http://schemas.datacontract.org/2004/07/EP.Core.Services.AdminGatewayService.API.Contracts.Data", type = JAXBElement.class)
    protected JAXBElement<String> linkName;
    @XmlElementRef(name = "LinkSourceId", namespace = "http://schemas.datacontract.org/2004/07/EP.Core.Services.AdminGatewayService.API.Contracts.Data", type = JAXBElement.class)
    protected JAXBElement<String> linkSourceId;
    @XmlElementRef(name = "NewWindow", namespace = "http://schemas.datacontract.org/2004/07/EP.Core.Services.AdminGatewayService.API.Contracts.Data", type = JAXBElement.class)
    protected JAXBElement<String> newWindow;
    @XmlElementRef(name = "PrimaryProxy", namespace = "http://schemas.datacontract.org/2004/07/EP.Core.Services.AdminGatewayService.API.Contracts.Data", type = JAXBElement.class)
    protected JAXBElement<String> primaryProxy;
    @XmlElementRef(name = "ProxyURL", namespace = "http://schemas.datacontract.org/2004/07/EP.Core.Services.AdminGatewayService.API.Contracts.Data", type = JAXBElement.class)
    protected JAXBElement<String> proxyURL;
    @XmlElementRef(name = "QueryString", namespace = "http://schemas.datacontract.org/2004/07/EP.Core.Services.AdminGatewayService.API.Contracts.Data", type = JAXBElement.class)
    protected JAXBElement<String> queryString;
    @XmlElementRef(name = "ReqCatalogHoldingFields", namespace = "http://schemas.datacontract.org/2004/07/EP.Core.Services.AdminGatewayService.API.Contracts.Data", type = JAXBElement.class)
    protected JAXBElement<String> reqCatalogHoldingFields;
    @XmlElementRef(name = "ReqFields", namespace = "http://schemas.datacontract.org/2004/07/EP.Core.Services.AdminGatewayService.API.Contracts.Data", type = JAXBElement.class)
    protected JAXBElement<String> reqFields;
    @XmlElementRef(name = "SecondaryProxy", namespace = "http://schemas.datacontract.org/2004/07/EP.Core.Services.AdminGatewayService.API.Contracts.Data", type = JAXBElement.class)
    protected JAXBElement<String> secondaryProxy;
    @XmlElementRef(name = "ShowIfLocal", namespace = "http://schemas.datacontract.org/2004/07/EP.Core.Services.AdminGatewayService.API.Contracts.Data", type = JAXBElement.class)
    protected JAXBElement<String> showIfLocal;
    @XmlElement(name = "ShowOnCatalogHoldingTable")
    protected Boolean showOnCatalogHoldingTable;
    @XmlElement(name = "ShowOnControlPanel")
    protected Boolean showOnControlPanel;
    @XmlElement(name = "ShowOnDetailDisplay")
    protected Boolean showOnDetailDisplay;
    @XmlElement(name = "ShowOnLinkSource")
    protected Boolean showOnLinkSource;
    @XmlElement(name = "ShowOnPubFinderDetails")
    protected Boolean showOnPubFinderDetails;
    @XmlElement(name = "ShowOnPubFinderResults")
    protected Boolean showOnPubFinderResults;
    @XmlElement(name = "ShowOnPublicationList")
    protected Boolean showOnPublicationList;
    @XmlElement(name = "ShowOnResultList")
    protected Boolean showOnResultList;
    @XmlElement(name = "TargetUsesRefUrl")
    protected Boolean targetUsesRefUrl;
    @XmlElementRef(name = "UseProxy", namespace = "http://schemas.datacontract.org/2004/07/EP.Core.Services.AdminGatewayService.API.Contracts.Data", type = JAXBElement.class)
    protected JAXBElement<String> useProxy;
    @XmlElementRef(name = "WindowName", namespace = "http://schemas.datacontract.org/2004/07/EP.Core.Services.AdminGatewayService.API.Contracts.Data", type = JAXBElement.class)
    protected JAXBElement<String> windowName;
    @XmlElementRef(name = "WindowParams", namespace = "http://schemas.datacontract.org/2004/07/EP.Core.Services.AdminGatewayService.API.Contracts.Data", type = JAXBElement.class)
    protected JAXBElement<String> windowParams;

    /**
     * Gets the value of the baseURL property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getBaseURL() {
        return baseURL;
    }

    /**
     * Sets the value of the baseURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBaseURL(JAXBElement<String> value) {
        this.baseURL = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the encode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getEncode() {
        return encode;
    }

    /**
     * Sets the value of the encode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setEncode(JAXBElement<String> value) {
        this.encode = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the genre property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getGenre() {
        return genre;
    }

    /**
     * Sets the value of the genre property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setGenre(JAXBElement<String> value) {
        this.genre = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the hideHelperFor property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getHideHelperFor() {
        return hideHelperFor;
    }

    /**
     * Sets the value of the hideHelperFor property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setHideHelperFor(JAXBElement<String> value) {
        this.hideHelperFor = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the hideIfFullText property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHideIfFullText() {
        return hideIfFullText;
    }

    /**
     * Sets the value of the hideIfFullText property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHideIfFullText(Boolean value) {
        this.hideIfFullText = value;
    }

    /**
     * Gets the value of the linkCategory property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLinkCategory() {
        return linkCategory;
    }

    /**
     * Sets the value of the linkCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLinkCategory(JAXBElement<String> value) {
        this.linkCategory = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the linkIcon property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLinkIcon() {
        return linkIcon;
    }

    /**
     * Sets the value of the linkIcon property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLinkIcon(JAXBElement<String> value) {
        this.linkIcon = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the linkKey property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLinkKey() {
        return linkKey;
    }

    /**
     * Sets the value of the linkKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLinkKey(JAXBElement<String> value) {
        this.linkKey = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the linkName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLinkName() {
        return linkName;
    }

    /**
     * Sets the value of the linkName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLinkName(JAXBElement<String> value) {
        this.linkName = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the linkSourceId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLinkSourceId() {
        return linkSourceId;
    }

    /**
     * Sets the value of the linkSourceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLinkSourceId(JAXBElement<String> value) {
        this.linkSourceId = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the newWindow property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getNewWindow() {
        return newWindow;
    }

    /**
     * Sets the value of the newWindow property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setNewWindow(JAXBElement<String> value) {
        this.newWindow = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the primaryProxy property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPrimaryProxy() {
        return primaryProxy;
    }

    /**
     * Sets the value of the primaryProxy property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPrimaryProxy(JAXBElement<String> value) {
        this.primaryProxy = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the proxyURL property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getProxyURL() {
        return proxyURL;
    }

    /**
     * Sets the value of the proxyURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setProxyURL(JAXBElement<String> value) {
        this.proxyURL = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the queryString property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getQueryString() {
        return queryString;
    }

    /**
     * Sets the value of the queryString property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setQueryString(JAXBElement<String> value) {
        this.queryString = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the reqCatalogHoldingFields property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getReqCatalogHoldingFields() {
        return reqCatalogHoldingFields;
    }

    /**
     * Sets the value of the reqCatalogHoldingFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setReqCatalogHoldingFields(JAXBElement<String> value) {
        this.reqCatalogHoldingFields = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the reqFields property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getReqFields() {
        return reqFields;
    }

    /**
     * Sets the value of the reqFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setReqFields(JAXBElement<String> value) {
        this.reqFields = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the secondaryProxy property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSecondaryProxy() {
        return secondaryProxy;
    }

    /**
     * Sets the value of the secondaryProxy property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSecondaryProxy(JAXBElement<String> value) {
        this.secondaryProxy = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the showIfLocal property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getShowIfLocal() {
        return showIfLocal;
    }

    /**
     * Sets the value of the showIfLocal property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setShowIfLocal(JAXBElement<String> value) {
        this.showIfLocal = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the showOnCatalogHoldingTable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowOnCatalogHoldingTable() {
        return showOnCatalogHoldingTable;
    }

    /**
     * Sets the value of the showOnCatalogHoldingTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowOnCatalogHoldingTable(Boolean value) {
        this.showOnCatalogHoldingTable = value;
    }

    /**
     * Gets the value of the showOnControlPanel property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowOnControlPanel() {
        return showOnControlPanel;
    }

    /**
     * Sets the value of the showOnControlPanel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowOnControlPanel(Boolean value) {
        this.showOnControlPanel = value;
    }

    /**
     * Gets the value of the showOnDetailDisplay property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowOnDetailDisplay() {
        return showOnDetailDisplay;
    }

    /**
     * Sets the value of the showOnDetailDisplay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowOnDetailDisplay(Boolean value) {
        this.showOnDetailDisplay = value;
    }

    /**
     * Gets the value of the showOnLinkSource property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowOnLinkSource() {
        return showOnLinkSource;
    }

    /**
     * Sets the value of the showOnLinkSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowOnLinkSource(Boolean value) {
        this.showOnLinkSource = value;
    }

    /**
     * Gets the value of the showOnPubFinderDetails property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowOnPubFinderDetails() {
        return showOnPubFinderDetails;
    }

    /**
     * Sets the value of the showOnPubFinderDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowOnPubFinderDetails(Boolean value) {
        this.showOnPubFinderDetails = value;
    }

    /**
     * Gets the value of the showOnPubFinderResults property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowOnPubFinderResults() {
        return showOnPubFinderResults;
    }

    /**
     * Sets the value of the showOnPubFinderResults property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowOnPubFinderResults(Boolean value) {
        this.showOnPubFinderResults = value;
    }

    /**
     * Gets the value of the showOnPublicationList property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowOnPublicationList() {
        return showOnPublicationList;
    }

    /**
     * Sets the value of the showOnPublicationList property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowOnPublicationList(Boolean value) {
        this.showOnPublicationList = value;
    }

    /**
     * Gets the value of the showOnResultList property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowOnResultList() {
        return showOnResultList;
    }

    /**
     * Sets the value of the showOnResultList property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowOnResultList(Boolean value) {
        this.showOnResultList = value;
    }

    /**
     * Gets the value of the targetUsesRefUrl property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTargetUsesRefUrl() {
        return targetUsesRefUrl;
    }

    /**
     * Sets the value of the targetUsesRefUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTargetUsesRefUrl(Boolean value) {
        this.targetUsesRefUrl = value;
    }

    /**
     * Gets the value of the useProxy property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getUseProxy() {
        return useProxy;
    }

    /**
     * Sets the value of the useProxy property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setUseProxy(JAXBElement<String> value) {
        this.useProxy = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the windowName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getWindowName() {
        return windowName;
    }

    /**
     * Sets the value of the windowName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setWindowName(JAXBElement<String> value) {
        this.windowName = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the windowParams property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getWindowParams() {
        return windowParams;
    }

    /**
     * Sets the value of the windowParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setWindowParams(JAXBElement<String> value) {
        this.windowParams = ((JAXBElement<String> ) value);
    }

}
