//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.26 at 10:34:50 AM EDT 
//


package hello.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GetFTFProfileResult" type="{http://schemas.datacontract.org/2004/07/EP.Core.Services.AdminGatewayService.API.Contracts.Data}ProfileFTFSettings" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getFTFProfileResult"
})
@XmlRootElement(name = "GetFTFProfileResponse", namespace = "http://tempuri.org/")
public class GetFTFProfileResponse {

    @XmlElementRef(name = "GetFTFProfileResult", namespace = "http://tempuri.org/", type = JAXBElement.class)
    protected JAXBElement<ProfileFTFSettings> getFTFProfileResult;

    /**
     * Gets the value of the getFTFProfileResult property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ProfileFTFSettings }{@code >}
     *     
     */
    public JAXBElement<ProfileFTFSettings> getGetFTFProfileResult() {
        return getFTFProfileResult;
    }

    /**
     * Sets the value of the getFTFProfileResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ProfileFTFSettings }{@code >}
     *     
     */
    public void setGetFTFProfileResult(JAXBElement<ProfileFTFSettings> value) {
        this.getFTFProfileResult = ((JAXBElement<ProfileFTFSettings> ) value);
    }

}
