//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.26 at 10:34:50 AM EDT 
//


package hello.wsdl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RequestStrategy.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RequestStrategy">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="NoChildren"/>
 *     &lt;enumeration value="AllChildren"/>
 *     &lt;enumeration value="DistinctChildren"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RequestStrategy")
@XmlEnum
public enum RequestStrategy {

    @XmlEnumValue("NoChildren")
    NO_CHILDREN("NoChildren"),
    @XmlEnumValue("AllChildren")
    ALL_CHILDREN("AllChildren"),
    @XmlEnumValue("DistinctChildren")
    DISTINCT_CHILDREN("DistinctChildren");
    private final String value;

    RequestStrategy(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RequestStrategy fromValue(String v) {
        for (RequestStrategy c: RequestStrategy.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
