//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.26 at 10:34:50 AM EDT 
//


package hello.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RequestComposite complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequestComposite">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.datacontract.org/2004/07/EP.Core.Services.AdminGatewayService.API.Contracts.Data}RequestComponent">
 *       &lt;sequence>
 *         &lt;element name="RequestComponents" type="{http://schemas.datacontract.org/2004/07/EP.Core.Services.AdminGatewayService.API.Contracts.Data}ArrayOfRequestComponent" minOccurs="0"/>
 *         &lt;element name="RequestStrategy" type="{http://schemas.datacontract.org/2004/07/EP.Core.Services.AdminGatewayService.API.Contracts.Data}RequestStrategy" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestComposite", propOrder = {
    "requestComponents",
    "requestStrategy"
})
@XmlSeeAlso({
    FilterCollectionIdRequests.class,
    ProfileAttributeRequests.class,
    CustomLinkRequest.class,
    CustomLinkRequests.class,
    MouseOverTextRequests.class,
    LinkTextRequests.class,
    AuthHelperTextRequests.class
})
public class RequestComposite
    extends RequestComponent
{

    @XmlElementRef(name = "RequestComponents", namespace = "http://schemas.datacontract.org/2004/07/EP.Core.Services.AdminGatewayService.API.Contracts.Data", type = JAXBElement.class)
    protected JAXBElement<ArrayOfRequestComponent> requestComponents;
    @XmlElement(name = "RequestStrategy")
    protected RequestStrategy requestStrategy;

    /**
     * Gets the value of the requestComponents property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfRequestComponent }{@code >}
     *     
     */
    public JAXBElement<ArrayOfRequestComponent> getRequestComponents() {
        return requestComponents;
    }

    /**
     * Sets the value of the requestComponents property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfRequestComponent }{@code >}
     *     
     */
    public void setRequestComponents(JAXBElement<ArrayOfRequestComponent> value) {
        this.requestComponents = ((JAXBElement<ArrayOfRequestComponent> ) value);
    }

    /**
     * Gets the value of the requestStrategy property.
     * 
     * @return
     *     possible object is
     *     {@link RequestStrategy }
     *     
     */
    public RequestStrategy getRequestStrategy() {
        return requestStrategy;
    }

    /**
     * Sets the value of the requestStrategy property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestStrategy }
     *     
     */
    public void setRequestStrategy(RequestStrategy value) {
        this.requestStrategy = value;
    }

}
