//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.26 at 10:34:50 AM EDT 
//


package hello.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UserDisplayLimiters complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserDisplayLimiters">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UserCommonLimiters" type="{http://schemas.datacontract.org/2004/07/EP.Core.Services.AdminGatewayService.Domain.UserProfile.Contracts.Data}ArrayOfUserLimiter" minOccurs="0"/>
 *         &lt;element name="UserDbLimiters" type="{http://schemas.datacontract.org/2004/07/EP.Core.Services.AdminGatewayService.Domain.UserProfile.Contracts.Data}ArrayOfUserDbLimiter" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserDisplayLimiters", namespace = "http://schemas.datacontract.org/2004/07/EP.Core.Services.AdminGatewayService.Domain.UserProfile.Contracts.Data", propOrder = {
    "userCommonLimiters",
    "userDbLimiters"
})
public class UserDisplayLimiters {

    @XmlElementRef(name = "UserCommonLimiters", namespace = "http://schemas.datacontract.org/2004/07/EP.Core.Services.AdminGatewayService.Domain.UserProfile.Contracts.Data", type = JAXBElement.class)
    protected JAXBElement<ArrayOfUserLimiter> userCommonLimiters;
    @XmlElementRef(name = "UserDbLimiters", namespace = "http://schemas.datacontract.org/2004/07/EP.Core.Services.AdminGatewayService.Domain.UserProfile.Contracts.Data", type = JAXBElement.class)
    protected JAXBElement<ArrayOfUserDbLimiter> userDbLimiters;

    /**
     * Gets the value of the userCommonLimiters property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfUserLimiter }{@code >}
     *     
     */
    public JAXBElement<ArrayOfUserLimiter> getUserCommonLimiters() {
        return userCommonLimiters;
    }

    /**
     * Sets the value of the userCommonLimiters property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfUserLimiter }{@code >}
     *     
     */
    public void setUserCommonLimiters(JAXBElement<ArrayOfUserLimiter> value) {
        this.userCommonLimiters = ((JAXBElement<ArrayOfUserLimiter> ) value);
    }

    /**
     * Gets the value of the userDbLimiters property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfUserDbLimiter }{@code >}
     *     
     */
    public JAXBElement<ArrayOfUserDbLimiter> getUserDbLimiters() {
        return userDbLimiters;
    }

    /**
     * Sets the value of the userDbLimiters property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfUserDbLimiter }{@code >}
     *     
     */
    public void setUserDbLimiters(JAXBElement<ArrayOfUserDbLimiter> value) {
        this.userDbLimiters = ((JAXBElement<ArrayOfUserDbLimiter> ) value);
    }

}
